routes:
  - path: "/books"
    method: GET
    exec: |
      cat /tmp/books
  - path: "/books/:id"
    method: GET
    exec: |
      BOOK=$(cat /tmp/books | grep "^$PARAM_ID," | cut -d',' -f2)
      [ -z "$BOOK" ] && echo 404 && exit 1
      echo $BOOK
  - path: "/books"
    method: POST
    exec: |
      ID=$(echo $(expr $((cat /tmp/books || echo 0) | tail -1 | cut -d',' -f1) + 1))
      NAME=$(cat -)
      echo "$ID,$NAME" >> /tmp/books
